# Generated by Django 2.2.3 on 2019-07-03 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20190703_1647'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_series_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_series_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postseries',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='postseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='series.Series'),
        ),
    ]
