# Generated by Django 2.2.3 on 2019-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AC', 'fa fa-check-circle'), ('DN', 'fa fa-backspace'), ('ACL', 'fa fa-ban'), ('INS', 'fa fa-file-import'), ('DEL', 'fa fa-trashe'), ('UPD', 'fa fa-user-edit'), ('DEA', 'fa fa-user-slash')], max_length=3, verbose_name='Action')),
                ('content', models.CharField(max_length=500, verbose_name='Content')),
                ('url', models.CharField(max_length=500, verbose_name='Content')),
            ],
        ),
    ]
