# Generated by Django 2.2.3 on 2019-07-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_deative',
            new_name='is_deactive',
        ),
    ]
