# Generated by Django 2.2.3 on 2019-07-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190721_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deactive',
        ),
    ]
