# Generated by Django 2.2.3 on 2019-07-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('post_stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststars',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='posts.Post'),
        ),
    ]
